# Generated by Django 3.1.1 on 2020-10-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_auth',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_auth',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
