# Generated by Django 3.1.1 on 2020-10-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0002_auto_20201007_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music_field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('music_file', models.FileField(upload_to='musicFile/')),
            ],
        ),
    ]
